### ISSUE TITLE
 Request.prototype.closed = function closed() Error

### ISSUE THREAD

**Issue by dupont-indra** [OfficeDev/Microsoft-Teams-Samples#1023]
C:\Work\Projects\SafeSpec\Demo_nodejs_echoBot\demo-echo-bot\node_modules\restify\lib\request.js:848

Stack Trace:
TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (C:\Work\Projects\SafeSpec\Demo_nodejs_echoBot\demo-echo-bot\node_modules\restify\lib\request.js:848:30)
    at Object.<anonymous> (C:\Work\Projects\SafeSpec\Demo_nodejs_echoBot\demo-echo-bot\node_modules\restify\lib\server.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (C:\Work\Projects\SafeSpec\Demo_nodejs_echoBot\demo-echo-bot\node_modules\restify\lib\index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.9.0

**Comment by Prasad-MSFT** [comment]
@dupont-indra - Could you please provide more details on your issue? Are you getting this error while building the sample?
