### ISSUE TITLE
bot-conversation => nodejs sample is throwing error: Node.js v18.16.1 [nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by ChetanSharma-msft** [OfficeDev/Microsoft-Teams-Samples#1089]
bot-conversation => nodejs sample is throwing error: Node.js v18.16.1 [nodemon] app crashed - waiting for file changes before starting...

Error details:
C:\Users\v-chetsharma\source\repos\Microsoft-Teams-Samples\samples\bot-conversation\nodejs\node_modules\botbuilder-core\lib\turnContext.js:391
                    this.responded = true;
                                   ^

TypeError: Cannot perform 'set' on a proxy that has been revoked
    at Proxy.<anonymous> (C:\Users\v-chetsharma\source\repos\Microsoft-Teams-Samples\samples\bot-conversation\nodejs\node_modules\botbuilder-core\lib\turnContext.js:391:36)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\v-chetsharma\source\repos\Microsoft-Teams-Samples\samples\bot-conversation\nodejs\node_modules\botbuilder-core\lib\turnContext.js:9:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.1
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
We checked this in Node v18.16.1. It is working fine at our end without any issues.
