### ISSUE TITLE
Not working for user assigned MSI apptype

### ISSUE THREAD

**Issue by arshad98786** [OfficeDev/Microsoft-Teams-Samples#1496]
Hi Team,

I’m trying to send a request using Python without providing an app password, as the authentication method is set to User Assigned Managed Identity (userAssignedMSI). However, the Python code sample provided still expects an app password, which should not be required for this authentication type.

Could you please help me resolve this issue at the earliest?

Thanks and Regards,
Arshad Ali S. K.

**Comment by Prasad-MSFT** [comment]
To authenticate using a User Assigned Managed Identity (userAssignedMSI) in Azure without providing an app password, you can use the azure-identity library in Python. This library allows you to authenticate using managed identities, which is a secure way to access Azure resources without needing to manage credentials.
https://learn.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#managed-identity-support

Also refer: https://learn.microsoft.com/en-us/entra/msal/python/advanced/managed-identity

**Comment by MKP-Sonata** [comment]
Hi @Prasad-MSFT ,

We tried the recommended solution but we are getting the same error we faced before. 
I am pasting the error message below

`2024-12-30T08:21:06.4125202Z ERROR:root:Error processing message: Failed to get access token with error: invalid_client, error_description: AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type. Trace ID: 8e5710cf-fb1c-4b48-bfae-8675d6c35100 Correlation ID: 4e744cf8-adc7-49fb-bb94-4b5fb4451f7a Timestamp: 2024-12-30 08:21:06Z
2024-12-30T08:21:06.4125847Z Traceback (most recent call last):
2024-12-30T08:21:06.4125885Z   File "/tmp/8dd26616c5a756c/bots/teams_conversation_bot.py", line 58, in on_message_activity
2024-12-30T08:21:06.4125907Z     await turn_context.send_activity(response)
2024-12-30T08:21:06.4125931Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/turn_context.py", line 174, in send_activity
2024-12-30T08:21:06.4125953Z     result = await self.send_activities([activity_or_text])
2024-12-30T08:21:06.4125974Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-30T08:21:06.4126001Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/turn_context.py", line 226, in send_activities
2024-12-30T08:21:06.4126069Z     return await self._emit(self._on_send_activities, output, logic())
2024-12-30T08:21:06.4126107Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-30T08:21:06.4126131Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/turn_context.py", line 304, in _emit
2024-12-30T08:21:06.4126155Z     return await logic
2024-12-30T08:21:06.4126176Z            ^^^^^^^^^^^
2024-12-30T08:21:06.4126199Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/turn_context.py", line 221, in logic
2024-12-30T08:21:06.4126224Z     responses = await self.adapter.send_activities(self, output)
2024-12-30T08:21:06.4126249Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-30T08:21:06.4126274Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/bot_framework_adapter.py", line 728, in send_activities
2024-12-30T08:21:06.4126295Z     raise error
2024-12-30T08:21:06.4126330Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/bot_framework_adapter.py", line 718, in send_activities
2024-12-30T08:21:06.4126353Z     response = await client.conversations.send_to_conversation(
2024-12-30T08:21:06.4126376Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-30T08:21:06.4126404Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botframework/connector/aio/operations_async/_conversations_operations_async.py", line 255, in send_to_conversation
2024-12-30T08:21:06.4126427Z     response = await self._client.async_send(
2024-12-30T08:21:06.4126453Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-30T08:21:06.4126478Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/msrest/async_client.py", line 115, in async_send
2024-12-30T08:21:06.4126500Z     pipeline_response = await self.config.pipeline.run(request, **kwargs)
2024-12-30T08:21:06.4126522Z                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-30T08:21:06.4126552Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/msrest/pipeline/async_abc.py", line 159, in run
2024-12-30T08:21:06.4126575Z     return await first_node.send(pipeline_request, **kwargs)  # type: ignore
2024-12-30T08:21:06.4126595Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-30T08:21:06.4126621Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/msrest/pipeline/async_abc.py", line 79, in send
2024-12-30T08:21:06.4126646Z     response = await self.next.send(request, **kwargs)  # type: ignore
2024-12-30T08:21:06.4126670Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-30T08:21:06.4126695Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/msrest/pipeline/async_requests.py", line 99, in send
2024-12-30T08:21:06.4126718Z     self._creds.signed_session(session)2024-12-30T08:21:06.4126756Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botframework/connector/auth/app_credentials.py", line 92, in signed_session
2024-12-30T08:21:06.4126781Z     auth_token = self.get_access_token()
2024-12-30T08:21:06.4126804Z                  ^^^^^^^^^^^^^^^^^^^^^^^
2024-12-30T08:21:06.4126830Z   File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botframework/connector/auth/microsoft_app_credentials.py", line 63, in get_access_token
2024-12-30T08:21:06.4126856Z     raise PermissionError(
2024-12-30T08:21:06.4126894Z PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type. Trace ID: 8e5710cf-fb1c-4b48-bfae-8675d6c35100 Correlation ID: 4e744cf8-adc7-49fb-bb94-4b5fb4451f7a Timestamp: 2024-12-30 08:21:06Z
2024-12-30T08:21:06.5315722Z ERROR:root:Error processing activity: Failed to get access token with error: invalid_client, error_description: AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type. Trace ID: 1fb0582e-fc6d-4351-ae91-a8aab6d17000 Correlation ID: 0950f1a0-e218-4ba2-8518-f632037d4937 Timestamp: 2024-12-30 08:21:06Z`

The above error is occurring for the below line of code.
`await turn_context.send_activity("This is a hardcoded reply")`


Could you please help out with this error we are facing.
Thank You.

**Comment by Prasad-MSFT** [comment]
@MKP-Sonata, we will check this with engineering team internally and will get back to you once we have any update to share. Thanks!

**Comment by arshad98786** [comment]
Hi Prasad,

Any update on the above issue?


Thanks

**Comment by Prasad-MSFT** [comment]
Hi @arshad98786 , at the moment, we have not received any updates from the engineering team. However, we are actively communicating and as soon as we receive any updates from them, we will notify you in this thread. Thank you!

**Comment by arshad98786** [comment]
Hi @Prasad-MSFT  

This is just to remind you. 


Thanks

**Comment by shahidattech** [comment]
@Prasad-MSFT 

I am fromt he Same team in Sonata Software, Bangalore
This is has become an urgent business showstopper, We are trying to introduce this to one of our prime Healthcare US client, We have Deployed the Code in Azure following the Microsoft provided document:  Bot Type: User Assigned Managed Identity, here is a sample code that is deployed: 

```
from botbuilder.schema import Activity
import json
from botbuilder.core import BotFrameworkAdapter,BotFrameworkAdapterSettings
from fastapi import Request, APIRouter
from fastapi import status
from fastapi.responses import JSONResponse  
from app.utils.logging import logger
from app.core.config import settings
from app.controller.echobot import EchoBot


# Initialize FastAPI app
router = APIRouter()

botadaptersettings = BotFrameworkAdapterSettings(
    app_id="69XXXXXXXXXXXXXX",
    channel_auth_tenant="7bXXXXXXXXXXXXXXX"
)

botadapter = BotFrameworkAdapter(botadaptersettings)
ebot = EchoBot()

@router.post("/")
async def messages(request: Request):
    try:
        # Log the raw request body
        raw_body = await request.body()
        logger.info(f"Raw Request Body: {raw_body}")
        
        # Ensure the body is not empty
        if not raw_body:
            logger.debug("Empty request body received.")
            return {"status": "Error", "message": "Empty request body."}

        # Parse the request body as JSON
        body_json = json.loads(raw_body)
        logger.info(f"Incoming Message: {body_json}")

        # Deserialize the incoming activity
        activity = Activity().deserialize(body_json)

        # Define the turn call function
        async def turn_call(turn_context):
            await ebot.on_turn(turn_context)
        
        # Process the activity using the bot adapter
        await botadapter.process_activity(activity, "", turn_call)

        return {"status": "Success", "message": "Activity processed successfully."}

    except json.JSONDecodeError as decode_err:
        logger.error(f"JSON decode error: {decode_err}")
        return {"status": "Error", "message": "Invalid JSON in request body."}

    except Exception as e:
        logger.error(f"Error processing activity: {e}")
        return {"status": "Error", "message": str(e)}

echobot.py


from botbuilder.core import TurnContext
from app.utils.logging import logger


class EchoBot:
    async def on_turn(self,turn_context:TurnContext):
        logger.info(f"===Incoming message{turn_context.activity.text}")
        await turn_context.send_activity("Hello from BOT testing...")
```



Messaging Endpoint is responding well from Swagger but When hitting from "Test in Webchat" on Azure
Getting this response:
{error: {code: "BotError", message: "Failed to send activity: bot returned an error"},…}
error
: 
{code: "BotError", message: "Failed to send activity: bot returned an error"}
code
: 
"BotError"
message
: 
"Failed to send activity: bot returned an error"
httpStatusCode
: 
403

Please arrange a solution, The SDK is not working as documented by MS, We are available for Call/meet on Teams/Skype or Phone +918017625345

My Sonata Email: shahid.syed@sonata-software.com

**Comment by Prasad-MSFT** [comment]
> Hi [@Prasad-MSFT](https://github.com/Prasad-MSFT) ,
> 
> We tried the recommended solution but we are getting the same error we faced before. I am pasting the error message below
> 
> `2024-12-30T08:21:06.4125202Z ERROR:root:Error processing message: Failed to get access token with error: invalid_client, error_description: AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type. Trace ID: 8e5710cf-fb1c-4b48-bfae-8675d6c35100 Correlation ID: 4e744cf8-adc7-49fb-bb94-4b5fb4451f7a Timestamp: 2024-12-30 08:21:06Z 2024-12-30T08:21:06.4125847Z Traceback (most recent call last): 2024-12-30T08:21:06.4125885Z File "/tmp/8dd26616c5a756c/bots/teams_conversation_bot.py", line 58, in on_message_activity 2024-12-30T08:21:06.4125907Z await turn_context.send_activity(response) 2024-12-30T08:21:06.4125931Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/turn_context.py", line 174, in send_activity 2024-12-30T08:21:06.4125953Z result = await self.send_activities([activity_or_text]) 2024-12-30T08:21:06.4125974Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-12-30T08:21:06.4126001Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/turn_context.py", line 226, in send_activities 2024-12-30T08:21:06.4126069Z return await self._emit(self._on_send_activities, output, logic()) 2024-12-30T08:21:06.4126107Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-12-30T08:21:06.4126131Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/turn_context.py", line 304, in _emit 2024-12-30T08:21:06.4126155Z return await logic 2024-12-30T08:21:06.4126176Z ^^^^^^^^^^^ 2024-12-30T08:21:06.4126199Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/turn_context.py", line 221, in logic 2024-12-30T08:21:06.4126224Z responses = await self.adapter.send_activities(self, output) 2024-12-30T08:21:06.4126249Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-12-30T08:21:06.4126274Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/bot_framework_adapter.py", line 728, in send_activities 2024-12-30T08:21:06.4126295Z raise error 2024-12-30T08:21:06.4126330Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botbuilder/core/bot_framework_adapter.py", line 718, in send_activities 2024-12-30T08:21:06.4126353Z response = await client.conversations.send_to_conversation( 2024-12-30T08:21:06.4126376Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-12-30T08:21:06.4126404Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botframework/connector/aio/operations_async/_conversations_operations_async.py", line 255, in send_to_conversation 2024-12-30T08:21:06.4126427Z response = await self._client.async_send( 2024-12-30T08:21:06.4126453Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-12-30T08:21:06.4126478Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/msrest/async_client.py", line 115, in async_send 2024-12-30T08:21:06.4126500Z pipeline_response = await self.config.pipeline.run(request, **kwargs) 2024-12-30T08:21:06.4126522Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-12-30T08:21:06.4126552Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/msrest/pipeline/async_abc.py", line 159, in run 2024-12-30T08:21:06.4126575Z return await first_node.send(pipeline_request, **kwargs) # type: ignore 2024-12-30T08:21:06.4126595Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-12-30T08:21:06.4126621Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/msrest/pipeline/async_abc.py", line 79, in send 2024-12-30T08:21:06.4126646Z response = await self.next.send(request, **kwargs) # type: ignore 2024-12-30T08:21:06.4126670Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2024-12-30T08:21:06.4126695Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/msrest/pipeline/async_requests.py", line 99, in send 2024-12-30T08:21:06.4126718Z self._creds.signed_session(session)2024-12-30T08:21:06.4126756Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botframework/connector/auth/app_credentials.py", line 92, in signed_session 2024-12-30T08:21:06.4126781Z auth_token = self.get_access_token() 2024-12-30T08:21:06.4126804Z ^^^^^^^^^^^^^^^^^^^^^^^ 2024-12-30T08:21:06.4126830Z File "/tmp/8dd26616c5a756c/antenv/lib/python3.12/site-packages/botframework/connector/auth/microsoft_app_credentials.py", line 63, in get_access_token 2024-12-30T08:21:06.4126856Z raise PermissionError( 2024-12-30T08:21:06.4126894Z PermissionError: Failed to get access token with error: invalid_client, error_description: AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type. Trace ID: 8e5710cf-fb1c-4b48-bfae-8675d6c35100 Correlation ID: 4e744cf8-adc7-49fb-bb94-4b5fb4451f7a Timestamp: 2024-12-30 08:21:06Z 2024-12-30T08:21:06.5315722Z ERROR:root:Error processing activity: Failed to get access token with error: invalid_client, error_description: AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type. Trace ID: 1fb0582e-fc6d-4351-ae91-a8aab6d17000 Correlation ID: 0950f1a0-e218-4ba2-8518-f632037d4937 Timestamp: 2024-12-30 08:21:06Z`
> 
> The above error is occurring for the below line of code. `await turn_context.send_activity("This is a hardcoded reply")`
> 
> Could you please help out with this error we are facing. Thank You.

Hi @MKP-Sonata , @arshad98786 - Is the sample running locally? Because according to engineering team's input, this will not work for a bot running on local machine. Managed Identity (including Federated Credentials) just won't work across networks.  The bot needs to be deployed to Azure.

**Comment by arshad98786** [comment]
Hi Prasad,


This is deployed on azure and we got this error, if we change the apptype
to single tenant or multi tenant its working but as we dont need multi or
single tenant, we deployed it with MSI. But its throwing the same error
which is asking credentials to be passed but as its MSI apptype we dont
have password for it.

So we need solution for this issue.


Thanks
Arshad

**Comment by Prasad-MSFT** [comment]
Hi @arshad98786, could you please refer this below sample which includes MSI and works fine?
Sample ref: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-message-reaction/python

Also, the PR for the bot-conversation-python sample to include the MSI has been raised. Sharing for reference.
https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1604
