### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by vermashreya2797** [OfficeDev/Microsoft-Teams-Samples#446]
Hi
I am unable to run your code locally and encountering a Syntax issue. Request for some help here. 

```
[nodemon] starting `babel-node src/app.js`
(node:7192) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\teamsadmin\Microsoft-Teams-Samples\samples\app-hello-world\nodejs\src\app.js:4
import path from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at loader (C:\Users\teamsadmin\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (C:\Users\teamsadmin\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at Object.<anonymous> (C:\Users\teamsadmin\AppData\Roaming\npm\node_modules\babel-cli\lib\_babel-node.js:154:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Meghana-MSFT** [comment]
Could you please confirm if you are setting up https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-hello-world/nodejs sample? Also please let us know in which step you are getting the error?

**Comment by vermashreya2797** [comment]
Hi
Yes I am setting up this code.
However, after I perform npm start in the local terminal as in this step: https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-nodejs?tutorial-step=2
I encounter the following error:
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at loader (C:\Users\teamsadmin\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (C:\Users\teamsadmin\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at Object.<anonymous> (C:\Users\teamsadmin\AppData\Roaming\npm\node_modules\babel-cli\lib\_babel-node.js:154:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
[nodemon] app crashed - waiting for file changes before starting...


Please suggest next steps. Appreciate your help.

Thanks

Shreya Verma | Partner Technology Strategist, ISV | Mumbai, India| Mobile: +91-9972507200
***@***.***

**Comment by Meghana-MSFT** [comment]
Can you please try adding "type": "module", in your package.json file.

**Comment by Meghana-MSFT** [comment]
Could you please confirm if your issue has been resolved?

**Comment by vermashreya2797** [comment]
Hi
The issue seems to persist, getting the exact same error.
Would be very helpful if we could plz get on a call.

Thanks

**Comment by Meghana-MSFT** [comment]
We tried the sample at https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-hello-world/nodejs and were able to run npm start successfully after using the command mentioned in Common Issues. Could you please follow the steps mentioned in the shared app-hello-world github sample.

**Comment by ChetanSharma-msft** [comment]
Hello @vermashreya2797 - Please let us know if you still have any query or shall we close this issue?

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any questions. Thank you.
