### ISSUE TITLE
Node.js Hello World sample fails to import 

### ISSUE THREAD

**Issue by zhihil** [OfficeDev/Microsoft-Teams-Samples#510]
I'm following the Hello World [tutorial](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-nodejs) on the Microsoft Teams documentation.

This tutorial is using the sample in `Microsoft-Teams-Samples/samples/app-hello-world/nodejs/`

Everything works fine until Step 6 of "Import the app package to Developer Portal" in this [part](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-nodejs?tutorial-step=3). When I click "Import app" and choose the `helloworldapp.zip` folder, I get this error message.  

<img width="766" alt="Screen Shot 2022-10-22 at 10 49 36 AM" src="https://user-images.githubusercontent.com/32404412/197345628-fe5f2e36-81e9-42cc-b750-50d4aa7e70b5.png">

If I click Import, the App does show up on my Apps pane:

<img width="1066" alt="Screen Shot 2022-10-22 at 10 50 00 AM" src="https://user-images.githubusercontent.com/32404412/197345647-07a03d6c-8398-488d-b79b-797e0cdbf15b.png">

However, if I open this App and go to **Publish > App package**, I can't see the `manifest.json` displayed. Instead I see this error screen:

<img width="1091" alt="Screen Shot 2022-10-22 at 10 50 22 AM" src="https://user-images.githubusercontent.com/32404412/197345670-ed3ceb43-32da-48a1-8797-fe596311b027.png">

I'm not sure if the tutorial steps are outdated or perhaps the sample is broken. Could someone take a look at the Hello World sample, reproduce the issue, and fix it?

**Comment by Nivedipa-MSFT** [comment]
@zhihil - We have checked this and we are able to get helloworldapp.zip in following path \Source\Repos\Microsoft-Teams-Samples\samples\app-hello-world\nodejs\manifest which is mentioned in below step:
![image](https://user-images.githubusercontent.com/92150070/197690827-0c9d6ba5-ea70-4f3e-b3e8-24a46f1b8761.png)
Are you also facing same problem? Are you manually creating zip package? Please check in manifest you have three files: manifest file, color icon file, outline icon file.

**Comment by Nivedipa-MSFT** [comment]
@zhihil - Could you please confirm is your issue resolved or are you still facing this issue?

**Comment by zhihil** [comment]
@Nivedipa-MSFT 

I'm not facing an issue of the `helloworldzpp.zip` being unable to be generated. By calling the `gulp` command I was able to generate the `.zip` file.

<img width="632" alt="Screen Shot 2022-11-02 at 11 57 34 AM" src="https://user-images.githubusercontent.com/32404412/199538739-638faa80-a5a8-46f5-a812-8c559e0122aa.png">

However, after unzipping the file, I was only able to see the `manifest.json`. 

<img width="452" alt="Screen Shot 2022-11-02 at 11 58 07 AM" src="https://user-images.githubusercontent.com/32404412/199538946-c1a6ec26-b7e7-447e-ba45-fe623d14b915.png">

When I reported this issue, I had also read up on the app package documentation and tried to manually generate `helloworldapp.zip` to see if that helped. Here is the command line output illustrating what I did:

```bash
➜  manifest git:(main) ✗ ls
color.png         helloworldapp.zip manifest.json     outline.png
➜  manifest git:(main) ✗ zip app.zip manifest.json outline.png color.png
  adding: manifest.json (deflated 64%)
  adding: outline.png (stored 0%)
  adding: color.png (deflated 4%)
```

The `outline.png` and `color.png` was taken from `Microsoft-Teams-Samples/samples/app-hello-world/nodejs/src/static/images` in the same project folder.

However, even manually creating the app package with all the required files, I still encountered the same error message:

<img width="607" alt="Screen Shot 2022-11-02 at 12 01 23 PM" src="https://user-images.githubusercontent.com/32404412/199539795-0cecd1ba-5db5-4825-a8cf-f98d00552c5f.png">

**Comment by Nivedipa-MSFT** [comment]
@zhihil - Thanks for sharing the details. We are also getting the same issue.
In manifest file the color and outline icon file name are different. Because of this we are getting "The file could not be found in the app package" error.
We will update the changes accordingly in sample and will raise a PR.
Could you please manually update the color and outline icon file name as color and outline and check if its working for you?
Please let us know if you are facing any further issue. Thanks.

**Comment by Nivedipa-MSFT** [comment]
@zhihil - Could you please confirm is your issue resolved or are you still facing any issue?

**Comment by zhihil** [comment]
@Nivedipa-MSFT 

I'm getting a error now after running `gulp`

```
➜  nodejs git:(v-mfurquan/app-hello-world-changes) ✗ gulp
[12:04:49] Using gulpfile ~/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/gulpfile.js
[12:04:49] Starting 'default'...
[12:04:49] Starting 'clean'...
[12:04:49] Finished 'clean' after 5.62 ms
[12:04:49] Starting 'generate-manifest'...
[12:04:49] Finished 'generate-manifest' after 4.28 ms
[12:04:49] Finished 'default' after 11 ms
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/src/manifest.json (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:642:26)
    at Glob.emit (node:events:527:28)
    at Glob.emit (node:domain:475:12)
    at Glob._finish (/Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/glob/glob.js:194:8)
    at done (/Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/glob/glob.js:179:14)
    at Glob._processSimple2 (/Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/glob/glob.js:688:12)
    at /Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/glob/glob.js:764:12)
Emitted 'error' event on Domain instance at:
    at DestroyableTransform.emit (node:domain:525:12)
    at Pumpify.emit (node:events:527:28)
    at Pumpify.emit (node:domain:475:12)
    at Pumpify.Duplexify._destroy (/Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/duplexify/index.js:191:15)
    at /Users/brennan-lu/Desktop/codeArchive/Microsoft-Teams-Samples/samples/app-hello-world/nodejs/node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  domainEmitter: DestroyableTransform {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: DestroyableTransform {
        _readableState: ReadableState {
          objectMode: true,
          highWaterMark: 16,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: Pumpify {
            _readableState: [ReadableState],
            readable: true,
            _events: [Object: null prototype],
            _eventsCount: 10,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: true,
            allowHalfOpen: true,
            _writable: [DestroyableTransform],
            _readable: [DestroyableTransform],
            _readable2: [DestroyableTransform],
            _autoDestroy: false,
            _forwardDestroy: false,
            _forwardEnd: true,
            _corked: 0,
            _ondrain: null,
            _drained: true,
            _forwarding: false,
            _unwrite: [Function: clear],
            _unread: [Function: clear],
            _ended: false,
            [Symbol(kCapture)]: false
          },
          pipesCount: 1,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          destroyed: false,
          defaultEncoding: 'utf8',
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: true,
        _events: [Object: null prototype] {
          end: [ [Function], [Function] ],
          prefinish: [Function: prefinish],
          unpipe: [Function: onunpipe],
          drain: [Function (anonymous)],
          error: [Function: onerror],
          close: [Function: bound onceWrapper] {
            listener: [Function: onclose]
          },
          finish: [Function: bound onceWrapper] {
            listener: [Function: onfinish]
          },
          data: [Function: ondata]
        },
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: true,
          highWaterMark: 16,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: true,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: true,
          bufferProcessing: false,
          onwrite: [Function (anonymous)],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: false,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: CorkedRequest {
            next: null,
            entry: null,
            finish: [Function (anonymous)]
          }
        },
        writable: true,
        allowHalfOpen: true,
        _transformState: {
          afterTransform: [Function: bound afterTransform],
          needTransform: true,
          transforming: false,
          writecb: null,
          writechunk: null,
          writeencoding: null
        },
        _destroyed: false,
        _transform: [Function (anonymous)],
        _flush: [Function (anonymous)],
        [Symbol(kCapture)]: false
      },
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [
        [Function: bound onceWrapper] { listener: [Function: onend] },
        [Function: bound onceWrapper] { listener: [Function: onend] }
      ],
      prefinish: [Function: prefinish],
      pipe: [Function: bound onceWrapper] { listener: [Function: onPipe] },
      data: [Function: ondata]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: CorkedRequest {
        next: null,
        entry: null,
        finish: [Function (anonymous)]
      }
    },
    writable: false,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: true,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: null
    },
    _destroyed: false,
    _transform: [Function: forward],
    _flush: [Function: flush],
    [Symbol(kCapture)]: false
  },
  domainThrown: false
}
```

**Comment by zhihil** [comment]
Also, in the `main` branch, I have tried to manually change the `"outline"` and `"color"` to `"outline.png" and `"color.png"` but this does not fix the issue. The `helloworldapp.zip` still does not contain `outline.png` or `color.png`. 

<img width="825" alt="Screen Shot 2022-11-04 at 12 13 41 PM" src="https://user-images.githubusercontent.com/32404412/200023992-173cbd58-8bec-460f-8719-e750ce6278d0.png">

**Comment by Nivedipa-MSFT** [comment]
@zhihil - Apologies for the delay. I have tried with gulp command and we are also getting same issue.
We will update the changes and will raise a PR accordingly.
Could you please manually create a zip package of color,outline and manifest file which is in appPackage folder and check if its working for you?
![image](https://user-images.githubusercontent.com/92150070/201020488-f959fb77-9173-4e5b-a8e5-63a8e70a14e2.png)

**Comment by Nivedipa-MSFT** [comment]
@zhihil - PR has merged successfully. Could you please check and confirm?
