### ISSUE TITLE
bot-conversation nodejs sample app crashes randomly when receiving onInstallationUpdateActivity

### ISSUE THREAD

**Issue by a1exwang** [OfficeDev/Microsoft-Teams-Samples#927]
Steps: 
- Follow the README and debug in Teams Toolkit and add bot app to a chat
- When the bot receives a conversation update activity, it will sometimes crash with

```
C:\Users\alexwang\Microsoft-Teams-Samples\samples\bot-conversation\nodejs\node_modules\botbuilder-core\lib\turnContext.js:391
                    this.responded = true;
                                   ^

TypeError: Cannot perform 'set' on a proxy that has been revoked
    at Proxy.<anonymous> (C:\Users\alexwang\Microsoft-Teams-Samples\samples\bot-conversation\nodejs\node_modules\botbuilder-core\lib\turnContext.js:391:36)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\alexwang\Microsoft-Teams-Samples\samples\bot-conversation\nodejs\node_modules\botbuilder-core\lib\turnContext.js:9:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

From a quick search, I found [other people can fix this by adding await](https://stackoverflow.com/a/55973153) and I added await to sendActivity and it seems it solves the issue. Should `await` be added to the sample by default?

```js
    async onInstallationUpdateActivity(context) {
        if (context.activity.conversation.conversationType === 'channel') {
            await context.sendActivity(MessageFactory.text(`Welcome to Microsoft Teams conversationUpdate events demo bot. This bot is configured in ${context.activity.conversation.name}`));
        } else {
            await context.sendActivity(MessageFactory.text('Welcome to Microsoft Teams conversationUpdate events demo bot.'));
        }
    }
```

Environment: Windows 10, Node.js 16.18.0

**Comment by Nivedipa-MSFT** [comment]
@a1exwang - Thanks for reporting your issue. We will check this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@a1exwang - We are trying this out but facing some issue. We will update you soon.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
