### ISSUE TITLE
SidePanel Sample Not Loading .env

### ISSUE THREAD

**Issue by ryankmcintyre** [OfficeDev/Microsoft-Teams-Samples#951]
When running the server in the [sidepanel sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-sidepanel/nodejs), the .env file is not loaded and required variables are thus missing.

To duplicate, run `npm start` from the `meetings-sidepanel/nodejs/server` directory. Resulting error is:
```
> teams-bot@1.0.0 start
> node server/index.js

/meetings-sidepanel/nodejs/server/Controllers/HomeController.js:10
const appID = env.MicrosoftAppId;
                  ^

TypeError: Cannot read properties of undefined (reading 'MicrosoftAppId')
    at Object.<anonymous> (/home/rmcintyre/github/Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/server/Controllers/HomeController.js:10:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/rmcintyre/github/Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/server/index.js:15:14)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
```
One possible fix is to replace line 4 in HomeController.js from
```
const configuration = require('dotenv').config();
```
to
```
const path = require('path');
const ENV_FILE = path.join(__dirname, '..', '.env');
const configuration = require('dotenv').config({ path: ENV_FILE });
```
That fixed it for me and allowed me to move on.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you. Thank you.

**Comment by ChetanSharma-msft** [comment]
Raised PR: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1009

**Comment by Meghana-MSFT** [comment]
The PR has been merged, we are closing this issue. Please feel free to reach out to us if you face any issue.
