### ISSUE TITLE
SidePanel Sample ClientApp Fails with Node 18

### ISSUE THREAD

**Issue by ryankmcintyre** [OfficeDev/Microsoft-Teams-Samples#953]
The [prereqs ](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-sidepanel/nodejs#prerequisites)for the SidePanel sample state node v10.14 or higher. Running the ClientApp on node v18.4.0 fails with the message:
```
Starting the development server...

/Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/ClientApp/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/ClientApp/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/ClientApp/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/ClientApp/node_modules/webpack/lib/NormalModule.js:452:10
    at /Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/ClientApp/node_modules/webpack/lib/NormalModule.js:323:13
    at /Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/ClientApp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /github/Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/ClientApp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/ClientApp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Microsoft-Teams-Samples/samples/meetings-sidepanel/nodejs/ClientApp/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
```
When I changed to node v16.20.2, the app ran fine.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you. Thank you.

**Comment by ChetanSharma-msft** [comment]
Raised PR: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/1009

**Comment by Meghana-MSFT** [comment]
The PR has been merged, we are closing this issue. Please feel free to reach out to us if you face any issue.
